name: prayer_timer
description: A Flutter package to display a customizable circular prayer time timer with progress bar for Islamic prayer times, supporting custom APIs and local storage.
version: 1.0.2
homepage: https://github.com/yourusername/prayer_timer

environment:
  sdk: '^3.7.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6